//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Scripts/Player/Input Package/NonStandardCursorNavigation.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Player/Input Package/NonStandardCursorNavigation.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @NonStandardCursorNavigation: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @NonStandardCursorNavigation()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""NonStandardCursorNavigation"",
    ""maps"": [
        {
            ""name"": ""NonStandardCursorNavigationMap"",
            ""id"": ""ee5d3f70-9015-4787-81fe-479c4bd8e9d4"",
            ""actions"": [
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""439d2998-8759-4654-9358-1c504bfcaaf2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickCursor"",
                    ""type"": ""Button"",
                    ""id"": ""33a84513-14a0-4e6b-9ca9-57f73b15cbfc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f4b81387-12f8-4818-8022-df59534621c1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a471126-69d9-4af0-87c6-b5e57193329f"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d60e08-3477-4ddf-8a3a-05560f2dcd4d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // NonStandardCursorNavigationMap
        m_NonStandardCursorNavigationMap = asset.FindActionMap("NonStandardCursorNavigationMap", throwIfNotFound: true);
        m_NonStandardCursorNavigationMap_MoveCursor = m_NonStandardCursorNavigationMap.FindAction("MoveCursor", throwIfNotFound: true);
        m_NonStandardCursorNavigationMap_ClickCursor = m_NonStandardCursorNavigationMap.FindAction("ClickCursor", throwIfNotFound: true);
    }

    ~@NonStandardCursorNavigation()
    {
        UnityEngine.Debug.Assert(!m_NonStandardCursorNavigationMap.enabled, "This will cause a leak and performance issues, NonStandardCursorNavigation.NonStandardCursorNavigationMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NonStandardCursorNavigationMap
    private readonly InputActionMap m_NonStandardCursorNavigationMap;
    private List<INonStandardCursorNavigationMapActions> m_NonStandardCursorNavigationMapActionsCallbackInterfaces = new List<INonStandardCursorNavigationMapActions>();
    private readonly InputAction m_NonStandardCursorNavigationMap_MoveCursor;
    private readonly InputAction m_NonStandardCursorNavigationMap_ClickCursor;
    /// <summary>
    /// Provides access to input actions defined in input action map "NonStandardCursorNavigationMap".
    /// </summary>
    public struct NonStandardCursorNavigationMapActions
    {
        private @NonStandardCursorNavigation m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public NonStandardCursorNavigationMapActions(@NonStandardCursorNavigation wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "NonStandardCursorNavigationMap/MoveCursor".
        /// </summary>
        public InputAction @MoveCursor => m_Wrapper.m_NonStandardCursorNavigationMap_MoveCursor;
        /// <summary>
        /// Provides access to the underlying input action "NonStandardCursorNavigationMap/ClickCursor".
        /// </summary>
        public InputAction @ClickCursor => m_Wrapper.m_NonStandardCursorNavigationMap_ClickCursor;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_NonStandardCursorNavigationMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="NonStandardCursorNavigationMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(NonStandardCursorNavigationMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="NonStandardCursorNavigationMapActions" />
        public void AddCallbacks(INonStandardCursorNavigationMapActions instance)
        {
            if (instance == null || m_Wrapper.m_NonStandardCursorNavigationMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NonStandardCursorNavigationMapActionsCallbackInterfaces.Add(instance);
            @MoveCursor.started += instance.OnMoveCursor;
            @MoveCursor.performed += instance.OnMoveCursor;
            @MoveCursor.canceled += instance.OnMoveCursor;
            @ClickCursor.started += instance.OnClickCursor;
            @ClickCursor.performed += instance.OnClickCursor;
            @ClickCursor.canceled += instance.OnClickCursor;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="NonStandardCursorNavigationMapActions" />
        private void UnregisterCallbacks(INonStandardCursorNavigationMapActions instance)
        {
            @MoveCursor.started -= instance.OnMoveCursor;
            @MoveCursor.performed -= instance.OnMoveCursor;
            @MoveCursor.canceled -= instance.OnMoveCursor;
            @ClickCursor.started -= instance.OnClickCursor;
            @ClickCursor.performed -= instance.OnClickCursor;
            @ClickCursor.canceled -= instance.OnClickCursor;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="NonStandardCursorNavigationMapActions.UnregisterCallbacks(INonStandardCursorNavigationMapActions)" />.
        /// </summary>
        /// <seealso cref="NonStandardCursorNavigationMapActions.UnregisterCallbacks(INonStandardCursorNavigationMapActions)" />
        public void RemoveCallbacks(INonStandardCursorNavigationMapActions instance)
        {
            if (m_Wrapper.m_NonStandardCursorNavigationMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="NonStandardCursorNavigationMapActions.AddCallbacks(INonStandardCursorNavigationMapActions)" />
        /// <seealso cref="NonStandardCursorNavigationMapActions.RemoveCallbacks(INonStandardCursorNavigationMapActions)" />
        /// <seealso cref="NonStandardCursorNavigationMapActions.UnregisterCallbacks(INonStandardCursorNavigationMapActions)" />
        public void SetCallbacks(INonStandardCursorNavigationMapActions instance)
        {
            foreach (var item in m_Wrapper.m_NonStandardCursorNavigationMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NonStandardCursorNavigationMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="NonStandardCursorNavigationMapActions" /> instance referencing this action map.
    /// </summary>
    public NonStandardCursorNavigationMapActions @NonStandardCursorNavigationMap => new NonStandardCursorNavigationMapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "NonStandardCursorNavigationMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="NonStandardCursorNavigationMapActions.AddCallbacks(INonStandardCursorNavigationMapActions)" />
    /// <seealso cref="NonStandardCursorNavigationMapActions.RemoveCallbacks(INonStandardCursorNavigationMapActions)" />
    public interface INonStandardCursorNavigationMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveCursor" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveCursor(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ClickCursor" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClickCursor(InputAction.CallbackContext context);
    }
}
